[Rainmeter]
Update=1000
AccurateText=1
DynamicWindowSize=1
BackgroundMode=2
SolidColor=0,0,0,1

[Metadata]
Name=Quotes
Author=Romit
Information=Quotes about race drivers.
Version=2.0

; ============================================================
; QUOTE
; ============================================================

[MeterQuote1]
Meter=String
X=36
Y=168
W=330
H=15
Text="S P E E D"
FontFace=BankGothic Md BT
FontSize=10
FontColor=255,255,255,255
StringStyle=Normal
AntiAlias=1
CharacterSpacing=1

[MeterQuote2]
Meter=String
X=36
Y=185
W=330
H=15
Text="B U I L D S"
FontFace=BankGothic Md BT
FontSize=10
FontColor=255,255,255,255
StringStyle=Normal
AntiAlias=1
CharacterSpacing=1

[MeterQuote3]
Meter=String
X=36
Y=202
W=330
H=15
Text="C H A R E C T E R"
FontFace=BankGothic Md BT
FontSize=10
FontColor=255,255,255,255
StringStyle=Normal
AntiAlias=1
CharacterSpacing=1

; ============================================================
; BOTTOM RED ACCENT
; ============================================================

[MeterRedBottom]
Meter=Shape
X=36
Y=230
Shape=Rectangle 0,0,70,4 | Fill Color 235,55,55,255 | StrokeWidth 0